maintainers:
 - burtonr
 - LucasRoesler
 - alexellis
 - ewilde
 - johnmccabe
 - jonatasbaldin
 - kenfdev
 - martindekov
 - rgee0
 - stefanprodan
 - viveksyngh
 - Waterdrips
 - utsavanand2

features:
 - dco_check
 - comments
 - pr_description_required
# - hacktoberfest
 - release_notes
 - rebase
 
mergers:
 - burtonr
 - LucasRoesler
 - alexellis
 - ewilde
 - johnmccabe
 - jonatasbaldin
 - kenfdev
 - martindekov
 - matipan
 - rgee0
 - stefanprodan
 - viveksyngh
 - Waterdrips
 - utsavanand2

must_approve:
- alexellis
- LucasRoesler

contributing_url: https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md

required_in_issues:
  - "## Expected Behaviour"
  - "## Current Behaviour"
  - "## Possible Solution"
  - "## Steps to Reproduce (for bugs)"
  - "## Context"
  - "## Your Environment"
